create or replace view v_monthly_report as
select a.USERID,
a.name,
b.CHECKTIME as tanggal,
MAX(TIME(b.CHECKTIME)) as maximum,
DATE(b.CHECKTIME) as tanggalonly,
	CASE WHEN DAY(b.CHECKTIME) = 1 then
  CASE
      WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
      ELSE 'X'
  END
 	END AS '1',

	CASE WHEN DAY(b.CHECKTIME) = 2 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '2',
	CASE WHEN DAY(b.CHECKTIME) = 3 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '3',
	CASE WHEN DAY(b.CHECKTIME) = 4 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '4',
	CASE WHEN DAY(b.CHECKTIME) = 5 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '5',
	CASE WHEN DAY(b.CHECKTIME) = 6 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '6',
	CASE WHEN DAY(b.CHECKTIME) = 7 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '7',
	CASE WHEN DAY(b.CHECKTIME) = 8 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '8',
	CASE WHEN DAY(b.CHECKTIME) = 9 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '9',
	CASE WHEN DAY(b.CHECKTIME) = 10 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '10',
	CASE WHEN DAY(b.CHECKTIME) = 11 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '11',
	CASE WHEN DAY(b.CHECKTIME) = 12 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '12',
	CASE WHEN DAY(b.CHECKTIME) = 13 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '13',
	CASE WHEN DAY(b.CHECKTIME) = 14 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '14',
	CASE WHEN DAY(b.CHECKTIME) = 15 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '15',
	CASE WHEN DAY(b.CHECKTIME) = 16 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '16',
	CASE WHEN DAY(b.CHECKTIME) = 17 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '17',
	CASE WHEN DAY(b.CHECKTIME) = 18 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '18',
	CASE WHEN DAY(b.CHECKTIME) = 19 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '19',
	CASE WHEN DAY(b.CHECKTIME) = 20 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '20',
	CASE WHEN DAY(b.CHECKTIME) = 21 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '21',
	CASE WHEN DAY(b.CHECKTIME) = 22 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '22',
	CASE WHEN DAY(b.CHECKTIME) = 23 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '23',
	CASE WHEN DAY(b.CHECKTIME) = 24 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '24',
	CASE WHEN DAY(b.CHECKTIME) = 25 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '25',
	CASE WHEN DAY(b.CHECKTIME) = 26 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '26',
	CASE WHEN DAY(b.CHECKTIME) = 27 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '27',
	CASE WHEN DAY(b.CHECKTIME) = 28 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '28',
	CASE WHEN DAY(b.CHECKTIME) = 29 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '29',
	CASE WHEN DAY(b.CHECKTIME) = 30 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
	END AS '30',
	CASE WHEN DAY(b.CHECKTIME) = 31 then
		CASE
		    WHEN DAY(b.CHECKTIME) IS NOT NULL then TIME(b.CHECKTIME)
		    ELSE 'X'
		END
 	END AS '31'
from userinfo a
join checkinout b
	on a.USERID = b.USERID GROUP BY b.CHECKTIME
